includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
epoch: 100
test_epoch: 5
test_episode: 600
batch_size: 128
episode_size: 1
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: 
  train: /opt/data/private/FSL_data/miniImageNet--ravi
  val: /opt/data/private/FSL_data/miniImageNet--ravi
  test: /opt/data/private/FSL_data/miniImageNet--ravi
#! optimizer
lr_scheduler:
  kwargs:
    T_max: 100
    eta_min: 0
  name: CosineAnnealingLR
optimizer:
  kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  name: SGD
  other: ~
#! backbone
backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
#! MLP layer
mlp_layer:
  kwargs: 
    in_dim: 1600
    hidden_dim: 1600
    out_dim: 1600
  name: Two_MLP_layer
  use: true
#! classifier
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_train_iter: 100
    num_class: 64
  name: BaselinePlus
#! result
result_root: ./results
#! other
log_test: false
val_per_epoch: 1
log_interval: 100
log_level: info
log_name: ~
log_paramerter: false
pretrain_path: ~
resume: false
resume_path: ~
save_interval: 10
save_part:
  - emb_func  
parallel_part:
  - emb_func