includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/RFS.yaml
- backbones/resnet18.yaml
#! device
device_ids: 1
n_gpu: 1
seed: 0
deterministic: true
#! basic
batch_size: 128
episode_size: 4
epoch: 100
test_epoch: 5
train_episode: 5000
test_episode: 600
shot_num: 1
way_num: 5
query_num: 15
test_shot: 1
test_way: 5
test_query: 15
image_size: 84
#! data
use_memory: false
augment: true
augment_times: 1
augment_times_query: 1
data_root: 
  train: /opt/data/private/FSL_data/miniImageNet--ravi
  val: /opt/data/private/FSL_data/miniImageNet--ravi
  test: /opt/data/private/FSL_data/miniImageNet--ravi
#! optimizer
lr_scheduler:
  kwargs:
    T_max: 100
    eta_min: 0
  name: CosineAnnealingLR
optimizer:
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  name: SGD
  other: null
#! backbone
backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
#! MLP layer
mlp_layer:
  kwargs: 
    in_dim: 512
    hidden_dim: 512
    out_dim: 512
  name: Two_MLP_layer
  use: true
#! classifier
classifier:
  kwargs:
    alpha: 0.5
    classifier_path: ./results/RFSModel-miniImageNet--ravi-resnet18-5-1-Sep-23-2021-15-24-44/checkpoints/classifier_best.pth
    emb_func_path: ./results/RFSModel-miniImageNet--ravi-resnet18-5-1-Sep-23-2021-15-24-44/checkpoints/emb_func_best.pth
    feat_dim: 512
    gamma: 0.5
    is_distill: false
    num_class: 64
  name: RFSModel
#! result
result_root: ./results
#! other
log_test: false
val_per_epoch: 1
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
pretrain_path: ~
resume: true
resume_path: ./results/RFSModel-miniImageNet--ravi-resnet18-5-1-Nov-27-2021-14-00-06
tb_scale: 8.333333333333334
tag: null
workers: 8
resume_path: ~
save_interval: 10
save_part:
  - emb_func  
parallel_part:
  - emb_func
  - classifier
  - distill_layers